apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.service.port }}
    name: http
    protocol: TCP