apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
  - {{ printf "%s.app.williambrittonjr.com" .Chart.Name }}
  http:
  - route:
    - destination:
        host: {{ printf "%s.svc.cluster.local" .Chart.Name }}