apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
  - {{ printf "%s.%s.svc.cluster.local" .Chart.Name .Chart.Name }}
  gateways:
  - istio-ingress/istio-ingress
  http:
  - match:
    - uri:
        prefix: /springboot-health
    route:
    - destination:
        port:
          number: 9080
        host: {{ printf "%s.%s.svc.cluster.local" .Chart.Name .Chart.Name }}