apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
  - {{ printf "%s.app.williambrittonjr.com" .Chart.Name }}
  - {{ printf "%s.kube.hyyercode.com" .Chart.Name }}
  gateways:
  - istio-ingress/ingress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.servicePort }}
        host: {{ printf "%s.%s.svc.cluster.local" .Chart.Name .Chart.Name }}