apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
  - "{{ .Chart.Name }}.app.williambrittonjr.com"
  http:
  - route:
    - destination:
        host: "{{ .Chart.Name }}.{{ .Values.Namespace }}.svc.cluster.local"